site_name: Pure Storage FlashBlade REST 1.10 Python SDK
pages:
- Overview:
    - Get Started: index.md
    - License: about/license.md
- Endpoints:
    - Authentication: AuthenticationApi.md
    - API Version: VersionApi.md
    - Login Banner: LoginBannerApi.md
    - APIs:
        - Admins: AdminsApi.md
        - Admins Cache: AdminsCacheApi.md
        - Alerts: AlertsApi.md
        - Alert Watchers: AlertWatchersApi.md
        - Alert Watchers Tests: AlertWatcherTest.md
        - Arrays: ArraysApi.md
        - Array Connections: ArrayConnectionsApi.md
        - Array Connection Keys: ArrayConnectionsApi.md
        - Array Connection Paths: ArrayConnectionsApi.md
        - Array Connection Performance Replication: ArrayConnectionsApi.md
        - Array Http Performances: ArraysApi.md
        - Array Nfs Performances: ArraysApi.md
        - Array Performances: ArraysApi.md
        - Array Performance Replication: ArraysApi.md
        - Array S3 Performances: ArraysApi.md
        - Array Spaces: ArraysApi.md
        - Audits: AuditsApi.md
        - Blades: BladeApi.md
        - Buckets: BucketsApi.md
        - Bucket Performances: BucketsApi.md
        - Bucket S3 Performances: BucketsApi.md
        - Bucket Replica Links: BucketReplicaLinksApi.md
        - Certificates: CertificatesApi.md
        - Certificate Uses: CertificatesApi.md
        - Certificate Groups: CertificateGroupsApi.md
        - Certificate Group Uses: CertificateGroupsApi.md
        - Directory Services: DirectoryServicesApi.md
        - Directory Services Roles: DirectoryServicesApi.md
        - Directory Services Tests: DirectoryServicesApi.md
        - Dns: DnsApi.md
        - File Systems: FileSystemsApi.md
        - File System Performances: FileSystemsApi.md
        - File System Policies: FileSystemsApi.md
        - File System Replica Links: FileSystemReplicaLinksApi.md
        - File System Replica Link Policies: FileSystemReplicaLinksApi.md
        - File System Replica Link Transfers: FileSystemReplicaLinksApi.md
        - File System Snapshots: FileSystemSnapshotsApi.md
        - File System Snapshot Policies: FileSystemSnapshotsApi.md
        - File System Snapshot Transfers: FileSystemSnapshotsApi.md
        - Hardware: HardwareApi.md
        - Hardware Connectors: HardwareConnectorsApi.md
        - Keytabs: KeytabsApi.md
        - Keytab Download: KeytabsApi.md
        - Keytab Upload: KeytabsApi.md
        - Lifecycle Rules: LifecycleRulesApi.md
        - Link Aggregation Groups: LinkAggregationGroupsApi.md
        - Logs: LogsApi.md
        - Network Interfaces: NetworkInterfacesApi.md
        - Object Store Access Keys: ObjectStoreAccessKeysApi.md
        - Object Store Accounts: ObjectStoreAccountsApi.md
        - Object Store Remote Credentials: ObjectStoreRemoteCredentialsApi.md
        - Object Store Users: ObjectStoreUsersApi.md
        - Policies: PoliciesApi.md
        - Policies for File Systems: PoliciesApi.md
        - Policies for File System Replica Links: PoliciesApi.md
        - Policies for File System Snapshots: PoliciesApi.md
        - Policy Members: PoliciesApi.md
        - Quotas for Groups: QuotasGroupsApi.md
        - Quota Notification Settings: QuotasSettingsApi.md
        - Quotas for Users: QuotasUsersApi.md
        - Roles: RolesApi.md
        - Smtp: SmtpApi.md
        - Snmp Agents: SnmpAgentsApi.md
        - Snmp Agents Mib: SnmpAgentsApi.md
        - Snmp Managers: SnmpManagersApi.md
        - Snmp Managers Test: SnmpManagersApi.md
        - Subnets: SubnetsApi.md
        - Support: SupportApi.md
        - Support Tests: SupportApi.md
        - Syslog Servers: SyslogApi.md
        - Syslog Servers Settings: SyslogApi.md
        - Syslog Servers Test: SyslogApi.md
        - Targets: TargetsApi.md
        - Target Performance Replication: TargetsApi.md
        - Usage for Groups: UsageGroupsApi.md
        - Usage for Users: UsageUsersApi.md

- Models:
    - Response:
        - Pagination Information: PaginationInfo.md
        - Error: ErrorResponse.md
        - API Version: VersionResponse.md
        - Login: LoginResponse.md
        - Admin: AdminResponse.md
        - Admin Cache: AdminCacheResponse.md
        - Alert: AlertResponse.md
        - Alert Watcher: AlertWatcherResponse.md
        - Alert Watcher Test: AlertWatcherTestResponse.md
        - Array: ArrayResponse.md
        - Array Connection: ArrayConnectionResponse.md
        - Array Connection Key: ArrayConnectionKeyResponse.md
        - Array Connection Path: ArrayConnectionPathResponse.md
        - Array Connection Performance Replication: RelationshipPerformanceReplicationResponse.md
        - Array Http Performance: ArrayHttpPerformanceResponse.md
        - Array Nfs Performance: ArrayNfsPerformanceResponse.md
        - Array Performance: ArrayPerformanceResponse.md
        - Array Performance Replication: ArrayPerformanceReplicationResponse.md
        - Array S3 Performance: ArrayS3PerformanceResponse.md
        - Array Space: ArraySpaceResponse.md
        - Audit: AuditResponse.md
        - Blade: BladeResponse.md
        - Bucket: BucketResponse.md
        - Bucket Performance: BucketPerformanceResponse.md
        - Bucket S3 Performance: BucketS3PerformanceResponse.md
        - Bucket Replica Link: BucketReplicaLinkResponse.md
        - Certificate: CertificateResponse.md
        - Certificate Group: CertificateGroupResponse.md
        - Certificate Group Use: CertificateGroupUseResponse.md
        - Certificate Use: CertificateUseResponse.md
        - Client Performance: ClientPerformanceResponse.md
        - Directory Service: DirectoryServiceResponse.md
        - Directory Service Roles: DirectoryServiceRolesResponse.md
        - Dns: DnsResponse.md
        - File System: FileSystemResponse.md
        - File System Performance: FileSystemPerformanceResponse.md
        - File System Replica Links: FileSystemReplicaLinkResponse.md
        - File System Snapshot: FileSystemSnapshotResponse.md
        - File System Snapshot Transfers: FileSystemSnapshotTransferResponse.md
        - Hardware: HardwareResponse.md
        - Hardware Connector: HardwareConnectorResponse.md
        - Keytab: KeytabResponse.md
        - Keytab Download Response: KeytabDownloadUploadResponse.md
        - Keytab Upload Response: KeytabDownloadUploadResponse.md
        - Lifecycle Rules Response: LifecycleRuleResponse.md
        - Link Aggregation Group: LinkAggregationGroupResponse.md
        - Login Banner Response: LoginBannerResponse.md
        - Logs: LogDownloadResponse.md
        - Member: MemberResponse.md
        - Network Interface: NetworkInterfaceResponse.md
        - Object: ObjectResponse.md
        - Object Store Access Key: ObjectStoreAccessKeyResponse.md
        - Object Store Account: ObjectStoreAccountResponse.md
        - Object Store Remote Credentials: ObjectStoreRemoteCredentialsResponse.md
        - Object Store User: ObjectStoreUserResponse.md
        - Performance Replication: PerformanceReplicationResponse.md
        - Policy: PolicyResponse.md
        - Policy Members: PolicyMemberResponse.md
        - Policy Members with Remote: PolicyMemberWithRemoteResponse.md
        - Policy Objects: PolicyObjectsResponse.md
        - Quotas or Usages for Groups: QuotasGroupResponse.md
        - Quota Notification Settings: QuotasSettingResponse.md
        - Quotas or Usages for Users: QuotasUserResponse.md
        - Roles: RoleResponse.md
        - Smtp: SmtpResponse.md
        - Snmp Agents: SnmpAgentResponse.md
        - Snmp Agent MIB: SnmpAgentMibResponse.md
        - Snmp Managers: SnmpManagerResponse.md
        - Snmp Manager Test: SnmpManagerTestResponse.md
        - Subnet: SubnetResponse.md
        - Support: SupportResponse.md
        - Syslog Servers Response: SyslogServerResponse.md
        - Syslog Servers Settings Response: SyslogServerSettingResponse.md
        - Syslog Servers Test Response: SyslogServerTestResponse.md
        - Target: TargetResponse.md
        - Test Result: TestResultResponse.md
    - Error: PureError.md
    - Space: Space.md
    - Admin:
        - Admin: Admin.md
        - Admin API Token: AdminApiToken.md
        - Admin Cache: AdminCache.md
    - Alert:
        - Alert: Alert.md
    - Alert Watcher:
        - Alert Watcher: AlertWatcher.md
        - Alert Watcher Post: AlertWatcherPost.md
        - Alert Watcher Test: AlertWatcherTest.md
    - Arrays:
        - Array Space: ArraySpace.md
        - Array Performance: ArrayPerformance.md
        - Array S3 Performance: ArrayS3Performance.md
        - Array Http Performance: ArrayHttpPerformance.md
        - Array Nfs Performance: ArrayNfsPerformance.md
        - Pure Array: PureArray.md
        - Client Performance: ClientPerformance.md
    - Array Connections:
        - Array Connection: ArrayConnection.md
        - Array Connection Key: ArrayConnectionKey.md
        - Array Connection Path: ArrayConnectionPath.md
        - Array Connection Post: ArrayConnectionPost.md
        - Array Connection Performance Replication: RelationshipPerformanceReplication.md
    - Audits:
        - Audit: Audit.md
    - Blade:
        - Blade: Blade.md
    - Bucket:
        - Bucket: Bucket.md
        - Bucket Patch: BucketPatch.md
        - Bucket Performance: BucketPerformance.md
        - Bucket Post: BucketPost.md
        - Bucket S3 Performance: BucketS3Performance.md
        - Lifecycle Rule: LifecycleRule.md
        - Lifecycle Rule Post: LifecycleRulePost.md
        - Lifecycle Rule Patch: LifecycleRulePatch.md
    - Bucket Replica Link:
        - Bucket Replica Link: BucketReplicaLink.md
        - Bucket Replica Link Post: BucketReplicaLinkPost.md
    - BuiltIn:
        - BuiltIn: BuiltIn.md
        - BuiltIn With Id: BuiltInWithId.md
    - Certificate:
        - Certificate: Certificate.md
        - Certificate Post: CertificatePost.md
        - Certificate Use: CertificateUse.md
    - Certificate Group:
        - Certificate Group: CertificateGroup.md
        - Certificate Group Use: CertificateGroupUse.md
    - Directory Service:
        - Directory Service: DirectoryService.md
        - Directory Service Role: DirectoryServiceRole.md
        - Directory Service Management Specific Attributes: DirectoryserviceManagement.md
        - Directory Service NFS Specific Attributes: DirectoryserviceNfs.md
        - Directory Service SMB Specific Attributes: DirectoryserviceSmb.md
        - Test Result: TestResult.md
    - Dns:
        - Dns: Dns.md
    - File System:
        - File System: FileSystem.md
        - File System Performance: FileSystemPerformance.md
        - NFS Protocol: NfsRule.md
        - Protocol Rule: ProtocolRule.md
        - SMB Rule: SmbRule.md
    - File System Replica Link:
        - Direction: Direction.md
        - File System Replica Link: FileSystemReplicaLink.md
        - Replica Link Built In: ReplicaLinkBuiltIn.md
        - Replication Performance: ReplicationPerformance.md
    - File System Snapshot:
        - File System Snapshot: FileSystemSnapshot.md
        - Snapshot Suffix: SnapshotSuffix.md
        - Snapshot Transfer: FileSystemSnapshotsTransfer.md
    - Fixed Reference:
        - Fixed Reference: FixedReference.md
        - Fixed Reference No Resource Type: FixedReferenceNoResourceType.md
        - Fixed Reference With Id: FixedReferenceWithId.md
        - Fixed Reference With Remote: FixedReferenceWithRemote.md
        - Resource Type: ResourceType.md
    - Hardware:
        - Hardware: Hardware.md
    - Hardware Connector:
        - Hardware Connector: HardwareConnector.md
    - Keytab:
        - Keytab: Keytab.md
    - Link Aggregation Group:
        - Link Aggregation Group: LinkAggregationGroup.md
        - Link Aggregation Group Patch: LinkAggregationGroupPatch.md
    - Location Reference:
        - Location Reference: LocationReference.md
    - Member:
        - Member: Member.md
        - Member Link: MemberLink.md
    - Network Interface:
        - Network Interface: NetworkInterface.md
    - Object Store:
        - Object Store Access Key: ObjectStoreAccessKey.md
        - Object Store Access Key Post: ObjectStoreAccessKeyPost.md
        - Object Store Account: ObjectStoreAccount.md
        - Object Store Remote Credentials: ObjectStoreRemoteCredentials.md
        - Object Store User: ObjectStoreUser.md
    - Permission:
        - Permission: Permission.md
    - Policy:
        - Policy: Policy.md
        - Policy Member: PolicyMember.md
        - Policy Member With Remote: PolicyMemberWithRemote.md
        - Policy Objects: PolicyObjects.md
        - Policy Patch: PolicyPatch.md
        - Policy Reference: PolicyReference.md
        - Policy Reference With Id: PolicyReferenceWithId.md
        - Policy Rule: PolicyRule.md
        - Resource Rule: ResourceRule.md
    - Pure Object:
        - Pure Object: PureObject.md
    - Quotas:
        - Group of Quota or Usage: QuotasgroupGroup.md
        - Quota or Usage for Group: QuotasGroup.md
        - Quota or Usage for User: QuotasUser.md
        - User of Quota or Usage: QuotasuserUser.md
        - Quota Notification Settings: QuotasSetting.md
    - Reference:
        - Reference: Reference.md
        - Reference Name: ReferenceName.md
    - Replication Performance:
        - Replication Performance: ReplicationPerformance.md
    - Resource:
        - Resource: Resource.md
    - Roles:
        - Role: Role.md
    - Smtp:
        - Smtp: Smtp.md
    - Snmp:
        - Snmp Agent: SnmpAgent.md
        - Snmp Agent MIB: SnmpAgentMib.md
        - Snmp Manager: SnmpManager.md
        - Snmp Manager Post: SnmpManagerPost.md
        - Snmp Manager Test: SnmpManagerTest.md
        - Snmp V2c Configuration: SnmpV2c.md
        - Snmp V3 Configuration: SnmpV3.md
    - Subnet:
        - Subnet: Subnet.md
    - Support:
        - Support: Support.md
        - Support Remote Assist Paths: SupportRemoteAssistPaths.md
    - Syslog:
        - Syslog Server: SyslogServer.md
        - Syslog Server Post or Patch: SyslogServerPostOrPatch.md
        - Syslog Server Settings: SyslogServerSetting.md
        - Syslog Server Settings Patch: SyslogServerSettingPatch.md
        - Syslog Server Test: SyslogServerTest.md
    - Target:
        - Target: Target.md
        - Target Post: TargetPost.md
        - Target Performance Replication: PerformanceReplication.md
theme: readthedocs
